### ISSUE TITLE
FASTA load error in PeptideMapping

### ISSUE THREAD

**Issue by vnaum** [compomics/compomics-utilities#30]
This fasta file fails to load -- while both sequences load OK separately:
```
>prf||1012271B
EAVVTQESALTTSPGGTVILTCRSSTGAVTTSNYANWVQEKPDHLFTGLIGGTSNRAPGVPVRFSGSLIG
DKAALTITGAQTEDDAMYFCALWYSTHFVFGGGTKVTVLG

>prf||1012271A
EAVVTQESALTTSPGGTVILTCRSSTGAVTTSNYANWVQEKPDHLFTGLIGGTSNRAPGVPVRFSGSLIG
DKAALTITGAQTEDDAMYFCALWYSTHFIFGSGTKVTVLG
```

This is how I run it:
```sh
java -cp /usr/local/utilities-4.11.17/utilities-4.11.17.jar com.compomics.util.experiment.identification.protein_inference.executable.PeptideMapping -p filtered_proteins.fasta peptides_132273.mzML.csv clstr_132273.mzML.csv
```
tested with 4.12.6, same result.
Peptides list might be arbitrary, apparently it never gets to load it.

**Comment by vnaum** [comment]
another example triggering the issue:
```
>pir||JC7976
MPFAAVDIQDDCGSPDVPQANPKRSKEEEEDRGDKNDHVKKRKKAKKDYQPNYFLSIPITNKKITTGIKV
LQNSILQQDKRLTKAMVGDGSFHITLLVMQLLNEDEVNIGTDALLELKPFVEEILEGKHLALPFQGIGTF
QGQVGFVKLADGDHVSALLEIAETAKRTFREKGILAGESRTFKPHLTFMKLSKAPMLRKKGVRKIEPGLY
EQFIDHRFGEELLYQIDLCSMLKKKQSNGYYHCESSIVIGEKDRREPEDAELVRLSKRLVENAVLKAAQQ
YLEETQNKKQPGEGNSTKAEEGDRNGDGSDNNRK

>pir||JC7975
MGGKWSKSSVVGWPTVRERMRRAEPAADGVGAASRDLEKHGAITSSNTAATTNAACAWLEQEEEEVGFPV
TPQVPLRPMTYKAAVDLSHFLKEKGGLEGLIHSQRRQDILDLWIYHTQGYFPDWQNYTPGPGVRYPLTFG
WCYKLVPVEPDKVEEANKGENTSLLHPVSLHGMDDPEREVEWRFDSRLAFHHVARELHPEYFKNC
```

**Comment by hbarsnes** [comment]
I'd recommend taking a look at our Database Help wiki (https://github.com/compomics/searchgui/wiki/DatabaseHelp), especially the Non Standard FASTA section: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta.

I assume that we are not able to extraxt the accession number due to the non-standard format and thus end up with two proteins with the same accession number. In that case, an easy search-and-replace to obtain the suggested generic format should solve the problem.

**Comment by brianbalgley** [comment]
I think he means to replace `pir||` with `generic|`. But if we simply remove `pir||` or `prf||` does it still fail?

**Comment by hbarsnes** [comment]
> I think he means to replace pir|| with generic|. But if we simply remove pir|| or prf|| does it still fail?

Both should work. For the latter the whole header will be used as the accession number. So the result should be the same.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by thedandychiggins** [comment]
I hope it's ok to post in this issue as I'm having the same problem.

I have headers from a MiSeq run (e.g. >MISEQ01:1:FCX:1:15:6329:1045 1:N:0:2) and I keep getting the error in the original post. I've tried changing them to '>generic|MISEQ01:1:FCX:1:15:6329:1045 1:N:0:2' but am still getting the error. Any help would be greatly appreciated.
